import { contextBridge } from 'electron';

import {
  championshipContract,
  laneControlContract,
  resultsContract,
  scoringDecisionsContract,
  resultVerificationContract,
  resultPublicationContract,
  publicationReviewPolicyContract,
  competitionAnnouncementsContract,
  incidentReportsContract,
  targetExaminationsContract,
  evidenceFilesContract,
  malfunctionScoreApplicationsContract,
  scoreCorrectionsContract,
  observationReviewsContract,
  reserveLaneTransfersContract,
  finalRecoveryFiringContract,
  rangeInterruptionsContract,
  relayReadinessContract,
  relayAthleteLifecycleContract,
  teamResultsContract,
  protestsContract,
  estBackupVerificationContract,
  backupCaptureReadinessContract,
  finalControlContract,
  finalOperationsContract,
  finalRecoveriesContract,
  qualificationMalfunctionsContract,
  adjudicationCasesContract,
  irregularShotCasesContract,
  operationalArchivesContract,
  estChampionshipInspectionsContract,
  postCompetitionEquipmentControlContract,
  eliminationPlanningContract,
  resultsBooksContract,
  startListsContract,
  mixedTeamFinalControlContract,
  squaddingContract,
  productionOperationsContract,
  mixedTeamTimeoutsContract,
  finalPlacementReviewContract,
  boardContract,
  shootoffContract,
  mqttContract,
  vistaContract,
  debugContract,
  eventsContract,
  athleteSanctionsContract,
  estComplaintsContract,
} from '@/shared/ipc/contracts';
import { equipmentRegistryContract } from '@/shared/ipc/contracts/equipmentRegistry.contract';
import { operationalProfilesContract } from '@/shared/ipc/contracts/operationalProfiles.contract';
import { operationalTemplatesContract } from '@/shared/ipc/contracts/operationalTemplates.contract';
import { operatorAccessContract } from '@/shared/ipc/contracts/operatorAccess.contract';
import type { ElectronAPI } from '@/shared/types/ElectronAPI';

import { buildProcedureBridge, buildEventBridge, buildAliasedBridge } from './buildPreloadAPI';

declare const __APP_VERSION__: string;

const electronAPI: ElectronAPI = {
  operatorAccess: buildProcedureBridge(operatorAccessContract),
  equipmentRegistry: buildProcedureBridge(equipmentRegistryContract),
  appVersion: __APP_VERSION__,
  queries: buildProcedureBridge(debugContract),
  mqtt: buildProcedureBridge(mqttContract),
  vista: buildProcedureBridge(vistaContract),

  // Championship uses aliased method names for 5 CRUD operations
  championship: buildAliasedBridge(championshipContract, {
    createChampionship: 'create',
    updateChampionship: 'update',
    deleteChampionship: 'delete',
    getChampionships: 'getAll',
    getChampionshipDetail: 'getDetail',
  }) as unknown as ElectronAPI['championship'],

  operationalProfiles: buildProcedureBridge(operationalProfilesContract),
  operationalTemplates: buildProcedureBridge(operationalTemplatesContract),
  athleteSanctions: buildProcedureBridge(athleteSanctionsContract),

  laneControl: buildProcedureBridge(laneControlContract),
  results: buildProcedureBridge(resultsContract),
  scoringDecisions: buildProcedureBridge(scoringDecisionsContract),
  resultVerification: buildProcedureBridge(resultVerificationContract),
  resultPublication: buildProcedureBridge(resultPublicationContract),
  publicationReviewPolicy: buildProcedureBridge(publicationReviewPolicyContract),
  competitionAnnouncements: buildProcedureBridge(competitionAnnouncementsContract),
  incidentReports: buildProcedureBridge(incidentReportsContract),
  targetExaminations: buildProcedureBridge(targetExaminationsContract),
  evidenceFiles: buildProcedureBridge(evidenceFilesContract),
  malfunctionScoreApplications: buildProcedureBridge(malfunctionScoreApplicationsContract),
  scoreCorrections: buildProcedureBridge(scoreCorrectionsContract),
  observationReviews: buildProcedureBridge(observationReviewsContract),
  reserveLaneTransfers: buildProcedureBridge(reserveLaneTransfersContract),
  finalRecoveryFiring: buildProcedureBridge(finalRecoveryFiringContract),
  estComplaints: buildProcedureBridge(estComplaintsContract),
  rangeInterruptions: buildProcedureBridge(rangeInterruptionsContract),
  relayReadiness: buildProcedureBridge(relayReadinessContract),
  relayAthleteLifecycle: buildProcedureBridge(relayAthleteLifecycleContract),
  teamResults: buildProcedureBridge(teamResultsContract),
  protests: buildProcedureBridge(protestsContract),
  estBackupVerification: buildProcedureBridge(estBackupVerificationContract),
  backupCaptureReadiness: buildProcedureBridge(backupCaptureReadinessContract),
  finalControl: buildProcedureBridge(finalControlContract),
  finalOperations: buildProcedureBridge(finalOperationsContract),
  finalRecoveries: buildProcedureBridge(finalRecoveriesContract),
  qualificationMalfunctions: buildProcedureBridge(qualificationMalfunctionsContract),
  adjudicationCases: buildProcedureBridge(adjudicationCasesContract),
  irregularShotCases: buildProcedureBridge(irregularShotCasesContract),
  operationalArchives: buildProcedureBridge(operationalArchivesContract),
  estChampionshipInspections: buildProcedureBridge(estChampionshipInspectionsContract),
  postCompetitionEquipmentControl: buildProcedureBridge(postCompetitionEquipmentControlContract),
  eliminationPlanning: buildProcedureBridge(eliminationPlanningContract),
  resultsBooks: buildProcedureBridge(resultsBooksContract),
  startLists: buildProcedureBridge(startListsContract),
  mixedTeamFinalControl: buildProcedureBridge(mixedTeamFinalControlContract),
  squadding: buildProcedureBridge(squaddingContract),
  productionOperations: buildProcedureBridge(productionOperationsContract),
  mixedTeamTimeouts: buildProcedureBridge(mixedTeamTimeoutsContract),
  finalPlacementReview: buildProcedureBridge(finalPlacementReviewContract),
  board: buildProcedureBridge(boardContract),
  shootoff: buildProcedureBridge(shootoffContract),
  on: buildEventBridge(eventsContract),
};

contextBridge.exposeInMainWorld('electronAPI', electronAPI);
