import { contextBridge } from 'electron';
import {
  championshipContract,
  laneControlContract,
  resultsContract,
  scoringDecisionsContract,
  resultVerificationContract,
  resultPublicationContract,
  competitionAnnouncementsContract,
  incidentReportsContract,
  targetExaminationsContract,
  rangeInterruptionsContract,
  relayReadinessContract,
  relayAthleteLifecycleContract,
  teamResultsContract,
  protestsContract,
  estBackupVerificationContract,
  finalControlContract,
  finalOperationsContract,
  finalRecoveriesContract,
  adjudicationCasesContract,
  irregularShotCasesContract,
  operationalArchivesContract,
  estChampionshipInspectionsContract,
  eliminationPlanningContract,
  resultsBooksContract,
  startListsContract,
  mixedTeamFinalControlContract,
  squaddingContract,
  productionOperationsContract,
  mixedTeamTimeoutsContract,
  finalPlacementReviewContract,
  boardContract,
  shootoffContract,
  mqttContract,
  debugContract,
  eventsContract,
} from '@/shared/ipc/contracts';
import type { ElectronAPI } from '@/shared/types/ElectronAPI';
import { buildProcedureBridge, buildEventBridge, buildAliasedBridge } from './buildPreloadAPI';

declare const __APP_VERSION__: string;

const electronAPI: ElectronAPI = {
  appVersion: __APP_VERSION__,
  queries: buildProcedureBridge(debugContract),
  mqtt: buildProcedureBridge(mqttContract),

  // Championship uses aliased method names for 5 CRUD operations
  championship: buildAliasedBridge(championshipContract, {
    createChampionship: 'create',
    updateChampionship: 'update',
    deleteChampionship: 'delete',
    getChampionships: 'getAll',
    getChampionshipDetail: 'getDetail',
  }) as unknown as ElectronAPI['championship'],

  laneControl: buildProcedureBridge(laneControlContract),
  results: buildProcedureBridge(resultsContract),
  scoringDecisions: buildProcedureBridge(scoringDecisionsContract),
  resultVerification: buildProcedureBridge(resultVerificationContract),
  resultPublication: buildProcedureBridge(resultPublicationContract),
  competitionAnnouncements: buildProcedureBridge(competitionAnnouncementsContract),
  incidentReports: buildProcedureBridge(incidentReportsContract),
  targetExaminations: buildProcedureBridge(targetExaminationsContract),
  rangeInterruptions: buildProcedureBridge(rangeInterruptionsContract),
  relayReadiness: buildProcedureBridge(relayReadinessContract),
  relayAthleteLifecycle: buildProcedureBridge(relayAthleteLifecycleContract),
  teamResults: buildProcedureBridge(teamResultsContract),
  protests: buildProcedureBridge(protestsContract),
  estBackupVerification: buildProcedureBridge(estBackupVerificationContract),
  finalControl: buildProcedureBridge(finalControlContract),
  finalOperations: buildProcedureBridge(finalOperationsContract),
  finalRecoveries: buildProcedureBridge(finalRecoveriesContract),
  adjudicationCases: buildProcedureBridge(adjudicationCasesContract),
  irregularShotCases: buildProcedureBridge(irregularShotCasesContract),
  operationalArchives: buildProcedureBridge(operationalArchivesContract),
  estChampionshipInspections: buildProcedureBridge(estChampionshipInspectionsContract),
  eliminationPlanning: buildProcedureBridge(eliminationPlanningContract),
  resultsBooks: buildProcedureBridge(resultsBooksContract),
  startLists: buildProcedureBridge(startListsContract),
  mixedTeamFinalControl: buildProcedureBridge(mixedTeamFinalControlContract),
  squadding: buildProcedureBridge(squaddingContract),
  productionOperations: buildProcedureBridge(productionOperationsContract),
  mixedTeamTimeouts: buildProcedureBridge(mixedTeamTimeoutsContract),
  finalPlacementReview: buildProcedureBridge(finalPlacementReviewContract),
  board: buildProcedureBridge(boardContract),
  shootoff: buildProcedureBridge(shootoffContract),
  on: buildEventBridge(eventsContract),
};

contextBridge.exposeInMainWorld('electronAPI', electronAPI);
