import type { IncidentReportOfficialRoleDto, RangeIncidentReportDto } from '@/shared/ipc/contracts';

interface IncidentReportSheetProps {
  report: RangeIncidentReportDto;
}

const SIGNATURE_ROLES: readonly IncidentReportOfficialRoleDto[] = [
  'RANGE_OFFICER',
  'COMPETITION_JURY_MEMBER',
  'RTS_OFFICER',
  'RTS_JURY_MEMBER',
  'RANKING_TECHNICAL_OFFICER',
];

export function IncidentReportSheet({ report }: IncidentReportSheetProps) {
  return (
    <article className="mx-auto max-w-[190mm] bg-white p-6 font-sans text-[11px] text-black">
      <header className="border-b-2 border-black pb-3 text-center">
        <div className="flex items-start justify-between gap-4">
          <span className="w-24 text-left text-xs font-bold">IR</span>
          <div>
            <h1 className="text-xl font-bold tracking-wide">RANGE INCIDENT REPORT</h1>
            <p className="mt-0.5 text-[10px]">Operational record generated by Saika Director</p>
          </div>
          <span className="w-24 text-right text-sm font-bold">{report.serialNumber}</span>
        </div>
      </header>

      {report.voided && (
        <div className="mt-3 border-2 border-red-700 p-2 text-center text-sm font-bold text-red-700">VOIDED</div>
      )}

      <section className="mt-4 grid grid-cols-4 border-l border-t border-black">
        <Cell label="Event" value={report.eventName} span={2} />
        <Cell label="Date / time of incident" value={formatDateTime(report.occurredAt)} span={2} />
        <Cell label="Relay" value={report.relayNumber?.toString() ?? ''} />
        <Cell label="Firing point" value={report.firingPointNumber?.toString() ?? ''} />
        <Cell label="Stage" value={report.stage ?? ''} />
        <Cell label="Series" value={report.series ?? ''} />
        <Cell label="Athlete" value={report.athleteName ?? ''} span={2} />
        <Cell label="Bib number" value={report.bibNumber ?? ''} />
        <Cell label="Nationality" value={report.nationality ?? ''} />
      </section>

      <section className="mt-4 space-y-3">
        <TextBox label="Brief details of incident" value={report.details} minHeight="min-h-24" />
        <TextBox label="Applicable ISSF rules" value={report.ruleReferences} />
        <TextBox label="Penalty / action imposed" value={report.penalty ?? ''} minHeight="min-h-12" />
        <TextBox label="Score amendment reference" value={report.scoreAmendmentReference ?? ''} />
      </section>

      <section className="mt-4">
        <h2 className="border-b border-black pb-1 text-xs font-bold uppercase">Official attestations</h2>
        <div className="mt-2 border-l border-t border-black">
          {SIGNATURE_ROLES.map((role) => {
            const signers = signaturesFor(report, role);
            return (
              <div key={role} className="grid grid-cols-[12rem_minmax(0,1fr)] border-b border-black">
                <div className="border-r border-black p-2 font-semibold">{formatRole(role)}</div>
                <div className="min-h-9 p-2">
                  {signers.map((signer) => (
                    <div key={signer.key}>
                      <div className="flex justify-between gap-4">
                        <span>{signer.name}</span>
                        <span>{formatDateTime(signer.at)}</span>
                      </div>
                      {signer.statement && <div className="text-[9px]">{signer.statement}</div>}
                    </div>
                  ))}
                </div>
              </div>
            );
          })}
        </div>
        <p className="mt-1 text-[9px]">
          Printed names above are audit attestations recorded in Director, not cryptographic electronic signatures.
        </p>
      </section>

      <section className="mt-4 grid grid-cols-2 gap-4">
        <div>
          <h2 className="border-b border-black pb-1 text-xs font-bold uppercase">Forwarding record</h2>
          <div className="mt-2 space-y-1">
            {report.entries.filter((entry) => entry.type === 'FORWARDED').length === 0 ? (
              <p>Not recorded</p>
            ) : (
              report.entries
                .filter((entry) => entry.type === 'FORWARDED')
                .map((entry) => (
                  <p key={entry.id}>
                    {entry.destination} · {entry.statement} · {entry.officialName} · {formatDateTime(entry.recordedAt)}
                  </p>
                ))
            )}
          </div>
        </div>
        <div>
          <h2 className="border-b border-black pb-1 text-xs font-bold uppercase">Linked score decisions</h2>
          <div className="mt-2 space-y-1">
            {report.linkedDecisions.length === 0 ? (
              <p>None recorded</p>
            ) : (
              report.linkedDecisions.map((decision) => (
                <p key={decision.id}>
                  {decision.type.replaceAll('_', ' ')} · Relay {decision.relayNumber} · Rule {decision.ruleReference} ·{' '}
                  {decision.active ? 'Active' : 'Audit history'} · {decision.publicRemark}
                </p>
              ))
            )}
          </div>
        </div>
      </section>

      {report.entries.some((entry) => entry.type === 'NOTE' || entry.type === 'VOID') && (
        <section className="mt-4">
          <h2 className="border-b border-black pb-1 text-xs font-bold uppercase">Additional audit entries</h2>
          <div className="mt-2 space-y-1">
            {report.entries
              .filter((entry) => entry.type === 'NOTE' || entry.type === 'VOID')
              .map((entry) => (
                <p key={entry.id}>
                  {entry.type} · {entry.statement} · {entry.officialName} · {formatDateTime(entry.recordedAt)}
                </p>
              ))}
          </div>
        </section>
      )}

      <footer className="mt-6 border-t border-black pt-2 text-[9px]">
        Source record ID: {report.id} · Created {formatDateTime(report.createdAt)}
      </footer>
    </article>
  );
}

function Cell({ label, value, span = 1 }: { label: string; value: string; span?: number }) {
  return (
    <div className={`border-b border-r border-black p-2 ${span === 2 ? 'col-span-2' : ''}`}>
      <div className="text-[9px] uppercase">{label}</div>
      <div className="mt-1 min-h-4 font-medium">{value}</div>
    </div>
  );
}

function TextBox({ label, value, minHeight = '' }: { label: string; value: string; minHeight?: string }) {
  return (
    <div className="border border-black p-2">
      <div className="text-[9px] uppercase">{label}</div>
      <div className={`mt-1 whitespace-pre-wrap font-medium ${minHeight}`}>{value}</div>
    </div>
  );
}

function signaturesFor(report: RangeIncidentReportDto, role: IncidentReportOfficialRoleDto) {
  const signers: Array<{ key: string; name: string; at: string; statement: string | null }> = [];
  if (report.initiatorRole === role) {
    signers.push({
      key: `initiator-${role}`,
      name: `${report.initiatorName} (initiator)`,
      at: report.createdAt,
      statement: null,
    });
  }
  for (const entry of report.entries) {
    if (entry.type === 'SIGNATURE' && entry.officialRole === role) {
      signers.push({ key: entry.id, name: entry.officialName, at: entry.recordedAt, statement: entry.statement });
    }
  }
  return signers;
}

function formatDateTime(value: string): string {
  return new Date(value).toLocaleString();
}

function formatRole(role: string): string {
  return role
    .toLowerCase()
    .split('_')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}
