export interface Quiz {
  image: string;
  answer: string;
}

export const quizList: Quiz[] = [
  { image: '/images/game-species/001_001.jpg', answer: 'マガモ' },
  { image: '/images/game-species/002_001.jpg', answer: 'カルガモ' },
  { image: '/images/game-species/003_001.jpg', answer: 'ヨシガモ' },
  { image: '/images/game-species/004_001.jpg', answer: 'コガモ' },
  { image: '/images/game-species/005_001.jpg', answer: 'オナガガモ' },
  { image: '/images/game-species/006_001.jpg', answer: 'ヒドリガモ' },
  { image: '/images/game-species/007_001.jpg', answer: 'ハシビロガモ' },
  { image: '/images/game-species/008_001.jpg', answer: 'ホシハジロ' },
  { image: '/images/game-species/009_001.jpg', answer: 'スズガモ' },
  { image: '/images/game-species/010_001.jpg', answer: 'キンクロハジロ' },
  { image: '/images/game-species/011_001.jpg', answer: 'クロガモ' },
  { image: '/images/game-species/012_001.jpg', answer: 'ゴイサギ' },
  { image: '/images/game-species/013_001.jpg', answer: 'バン' },
  { image: '/images/game-species/014_001.jpg', answer: 'タシギ' },
  { image: '/images/game-species/015_001.jpg', answer: 'ヤマシギ' },
  { image: '/images/game-species/016_001.jpg', answer: 'カワウ' },
  { image: '/images/game-species/017_001.jpg', answer: 'エゾライチョウ' },
  { image: '/images/game-species/019_001.jpg', answer: 'コジュケイ' },
  { image: '/images/game-species/020_001.jpg', answer: 'ヤマドリ' },
  { image: '/images/game-species/021_001.jpg', answer: 'キジ' },
  { image: '/images/game-species/022_001.jpg', answer: 'キジバト' },
  { image: '/images/game-species/023_001.jpg', answer: 'ニュウナイスズメ' },
  { image: '/images/game-species/024_001.jpg', answer: 'スズメ' },
  { image: '/images/game-species/025_001.jpg', answer: 'ヒヨドリ' },
  { image: '/images/game-species/026_001.jpg', answer: 'ムクドリ' },
  { image: '/images/game-species/027_001.jpg', answer: 'ミヤマガラス' },
  { image: '/images/game-species/028_001.jpg', answer: 'ハシボソガラス' },
  { image: '/images/game-species/029_001.jpg', answer: 'ハシブトガラス' },
  { image: '/images/game-species/101_001.jpg', answer: 'ノウサギ・ユキウサギ' },
  { image: '/images/game-species/102_001.jpg', answer: 'タイワンリス' },
  { image: '/images/game-species/103_001.jpg', answer: 'シマリス' },
  { image: '/images/game-species/104_001.jpg', answer: 'ヌートリア' },
  { image: '/images/game-species/105_001.jpg', answer: 'ヒグマ' },
  { image: '/images/game-species/106_001.jpg', answer: 'ツキノワグマ' },
  { image: '/images/game-species/107_001.jpg', answer: 'イノシシ' },
  { image: '/images/game-species/108_001.jpg', answer: 'ニホンジカ' },
  { image: '/images/game-species/109_001.jpg', answer: 'アライグマ' },
  { image: '/images/game-species/110_001.jpg', answer: 'タヌキ' },
  { image: '/images/game-species/111_001.jpg', answer: 'キツネ' },
  { image: '/images/game-species/112_001.jpg', answer: 'テン' },
  { image: '/images/game-species/113_001.jpg', answer: 'イタチ（オス）' },
  { image: '/images/game-species/114_001.jpg', answer: 'ミンク' },
  { image: '/images/game-species/115_001.jpg', answer: 'アナグマ' },
  { image: '/images/game-species/116_001.jpg', answer: 'ハクビシン' },
];
