export interface Quiz {
  image: string;
  answer: string;
  category: 'birds' | 'mammals';
}

export const quizList: Quiz[] = [
  { image: '/images/game-species/001_001.jpg', answer: 'マガモ', category: 'birds' },
  { image: '/images/game-species/002_001.jpg', answer: 'カルガモ', category: 'birds' },
  { image: '/images/game-species/003_001.jpg', answer: 'ヨシガモ', category: 'birds' },
  { image: '/images/game-species/004_001.jpg', answer: 'コガモ', category: 'birds' },
  { image: '/images/game-species/005_001.jpg', answer: 'オナガガモ', category: 'birds' },
  { image: '/images/game-species/006_001.jpg', answer: 'ヒドリガモ', category: 'birds' },
  { image: '/images/game-species/007_001.jpg', answer: 'ハシビロガモ', category: 'birds' },
  { image: '/images/game-species/008_001.jpg', answer: 'ホシハジロ', category: 'birds' },
  { image: '/images/game-species/009_001.jpg', answer: 'スズガモ', category: 'birds' },
  { image: '/images/game-species/010_001.jpg', answer: 'キンクロハジロ', category: 'birds' },
  { image: '/images/game-species/011_001.jpg', answer: 'クロガモ', category: 'birds' },
  { image: '/images/game-species/012_001.jpg', answer: 'ゴイサギ', category: 'birds' },
  { image: '/images/game-species/013_001.jpg', answer: 'バン', category: 'birds' },
  { image: '/images/game-species/014_001.jpg', answer: 'タシギ', category: 'birds' },
  { image: '/images/game-species/015_001.jpg', answer: 'ヤマシギ', category: 'birds' },
  { image: '/images/game-species/016_001.jpg', answer: 'カワウ', category: 'birds' },
  { image: '/images/game-species/017_001.jpg', answer: 'エゾライチョウ', category: 'birds' },
  { image: '/images/game-species/019_001.jpg', answer: 'コジュケイ', category: 'birds' },
  { image: '/images/game-species/020_001.jpg', answer: 'ヤマドリ', category: 'birds' },
  { image: '/images/game-species/021_001.jpg', answer: 'キジ', category: 'birds' },
  { image: '/images/game-species/022_001.jpg', answer: 'キジバト', category: 'birds' },
  { image: '/images/game-species/023_001.jpg', answer: 'ニュウナイスズメ', category: 'birds' },
  { image: '/images/game-species/024_001.jpg', answer: 'スズメ', category: 'birds' },
  { image: '/images/game-species/025_001.jpg', answer: 'ヒヨドリ', category: 'birds' },
  { image: '/images/game-species/026_001.jpg', answer: 'ムクドリ', category: 'birds' },
  { image: '/images/game-species/027_001.jpg', answer: 'ミヤマガラス', category: 'birds' },
  { image: '/images/game-species/028_001.jpg', answer: 'ハシボソガラス', category: 'birds' },
  { image: '/images/game-species/029_001.jpg', answer: 'ハシブトガラス', category: 'birds' },
  { image: '/images/game-species/101_001.jpg', answer: 'ノウサギ・ユキウサギ', category: 'mammals' },
  { image: '/images/game-species/102_001.jpg', answer: 'タイワンリス', category: 'mammals' },
  { image: '/images/game-species/103_001.jpg', answer: 'シマリス', category: 'mammals' },
  { image: '/images/game-species/104_001.jpg', answer: 'ヌートリア', category: 'mammals' },
  { image: '/images/game-species/105_001.jpg', answer: 'ヒグマ', category: 'mammals' },
  { image: '/images/game-species/106_001.jpg', answer: 'ツキノワグマ', category: 'mammals' },
  { image: '/images/game-species/107_001.jpg', answer: 'イノシシ', category: 'mammals' },
  { image: '/images/game-species/108_001.jpg', answer: 'ニホンジカ', category: 'mammals' },
  { image: '/images/game-species/109_001.jpg', answer: 'アライグマ', category: 'mammals' },
  { image: '/images/game-species/110_001.jpg', answer: 'タヌキ', category: 'mammals' },
  { image: '/images/game-species/111_001.jpg', answer: 'キツネ', category: 'mammals' },
  { image: '/images/game-species/112_001.jpg', answer: 'テン', category: 'mammals' },
  { image: '/images/game-species/113_001.jpg', answer: 'イタチ（オス）', category: 'mammals' },
  { image: '/images/game-species/114_001.jpg', answer: 'ミンク', category: 'mammals' },
  { image: '/images/game-species/115_001.jpg', answer: 'アナグマ', category: 'mammals' },
  { image: '/images/game-species/116_001.jpg', answer: 'ハクビシン', category: 'mammals' },
];
