name: Lock Threads

on:
  schedule:
    - cron: "0 2 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@89ae32b08ed1a541efecbab17912962a5e38981c # v6.0.2
        with:
          issue-inactive-days: 30
          pr-inactive-days: 30
          issue-lock-reason: resolved
          pr-lock-reason: resolved
          log-output: true
